spring:
  jpa:
    defer-datasource-initialization: true
    database-platform:
      org.hibernate.dialect.H2Dialect
   # show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
logging:
    level:
        org:
            springframework:
                # security: DEBUG
